package haiku

// These words sources from WordNet, downloaded from https://wordnet.princeton.edu/.
// See included LICENSE.WordNet.txt for details.

// Adjectives to be used in Haiku naming.
var Adjectives Words = []string{
	"acer", "after", "airy", "all-arounder", "angry", "archer", "arty", "ashy",
	"assaulter", "attacker", "backer", "bad", "baggy", "balky", "balmy", "bandy",
	"bargainer", "barmy", "batty", "baulky", "bawdy", "bayer", "beady", "beastly",
	"beater", "beefy", "beery", "bendy", "big", "bitchy", "biter", "bitty",
	"bleary", "bloodthirsty", "bloody", "blowsy", "blowy", "blowzy", "blue",
	"boner", "bonny", "bony", "boozy", "bosky", "bossy", "botchy", "bother",
	"bouncy", "bounder", "bower", "brainy", "brashy", "brassy", "brawny", "breathy",
	"breezy", "briny", "britisher", "broadcaster", "brooder", "broody", "bubbly",
	"buggy", "bulky", "bumpy", "bunchy", "burly", "burry", "burster", "bushy",
	"buster", "busty", "busy", "cagey", "camper", "canny", "canter", "canty",
	"caster", "catchy", "catty", "cer", "chancy", "chary", "chatty", "cheeky",
	"cheery", "cheesy", "chesty", "chewy", "chilly", "chintzy", "chippy", "choosy",
	"choppy", "chubby", "chuffy", "chummy", "chunky", "churchy", "clammy", "classy",
	"cleanly", "clerkly", "cloudy", "clubby", "clumsy", "cocky", "coder", "colly",
	"comely", "comfy", "corny", "costly", "costumer", "cosy", "counterfeiter",
	"courtly", "cozy", "crabby", "cracker", "crafty", "craggy", "cranky", "crasher",
	"crawly", "crazy", "creamer", "creamy", "creepy", "crispy", "crumbly", "crumby",
	"crummy", "crusty", "curly", "customer", "cute", "daffy", "dainty", "dandy",
	"deadly", "dealer", "deserter", "dewy", "dicey", "dim", "dimer", "dingy",
	"dinky", "dippy", "dirty", "dishy", "dizzy", "dodgy", "dopey", "dotty",
	"doughty", "doughy", "dowdy", "dowie", "downer", "downy", "dozy", "drab",
	"drafty", "draggy", "draughty", "dreamy", "dreary", "dreggy", "dresser",
	"dressy", "drippy", "drowsy", "dry", "dumpy", "dun", "dusky", "dusty", "early",
	"earthly", "earthy", "easter", "eastsider", "easy", "edger", "edgy", "eerie",
	"empty", "faker", "fancy", "fat", "fatty", "faulty", "feisty", "feller",
	"fiddly", "filmy", "filthy", "finny", "first-rater", "first-stringer", "fishy",
	"fit", "flabby", "flaggy", "flaky", "flasher", "flashy", "flat", "flaunty",
	"fledgy", "fleecy", "fleshly", "fleshy", "flighty", "flimsy", "flinty",
	"floaty", "floppy", "flossy", "fluffy", "fluky", "foamy", "foggy", "folder",
	"folksy", "foolhardy", "fore-and-after", "foreigner", "forest", "founder",
	"foxy", "fratchy", "freaky", "free", "frenchy", "friendly", "frisky", "frizzly",
	"frizzy", "frosty", "frouzy", "frowsy", "frowzy", "fruity", "funky", "funny",
	"furry", "fussy", "fusty", "fuzzy", "gabby", "gammy", "gamy", "gassy", "gaudy",
	"gauzy", "gawky", "ghastly", "ghostly", "giddy", "glad", "glassy", "glib",
	"gloomy", "glossy", "glum", "godly", "goer", "goner", "good", "goodly", "gooey",
	"goofy", "goosy", "gory", "gradely", "grader", "grainy", "grassy", "greasy",
	"greedy", "grim", "grisly", "gritty", "grizzly", "groggy", "groovy", "grotty",
	"grounder", "grouper", "grouty", "grubby", "grumpy", "guest", "guilty", "gummy",
	"gushy", "gusty", "gutsy", "hairy", "halfway", "halter", "hammy", "handy",
	"happy", "hardy", "hasty", "haughty", "hazy", "header", "heady", "healthy",
	"hearty", "heavy", "hefty", "hep", "herby", "hind", "hip", "hippy", "hoary",
	"holy", "homely", "homer", "homey", "horny", "horsy", "hot", "humpy", "hunger",
	"hungry", "husky", "icy", "inky", "insider", "interest", "jaggy", "jammy",
	"jaunty", "jazzy", "jerky", "jointer", "jolly", "juicy", "jumpy", "kindly",
	"kinky", "knotty", "knurly", "kooky", "lacy", "lairy", "laky", "lander",
	"lanky", "lathy", "layer", "lazy", "leafy", "leaky", "leary", "leer", "leery",
	"left-hander", "left-winger", "leggy", "lengthy", "ler", "leveler", "limy",
	"lippy", "liter", "lively", "liver", "loather", "lofty", "logy", "lonely",
	"loner", "loony", "loopy", "lordly", "lousy", "lovely", "lowlander", "lowly",
	"lucky", "lumpy", "luny", "lusty", "mad", "mainer", "maligner", "malty",
	"mangy", "manky", "manly", "mariner", "marshy", "massy", "matter", "maungy",
	"mazy", "mealy", "measly", "meaty", "meeter", "merry", "messy", "miffy",
	"mighty", "milcher", "milker", "milky", "mingy", "minter", "mirky", "miser",
	"misty", "mocker", "modeler", "modest", "moldy", "moody", "moony", "mothy",
	"mouldy", "mousy", "mouthy", "mucky", "muddy", "muggy", "multiplexer", "murky",
	"mushy", "musky", "muster", "musty", "muzzy", "nappy", "nasty", "natty",
	"naughty", "needy", "nervy", "newsy", "nifty", "nippy", "nitty", "noisy",
	"northeasterner", "norther", "northerner", "nosy", "number", "nutty", "off",
	"offer", "oily", "old-timer", "oliver", "oozy", "opener", "outsider",
	"overcomer", "overnighter", "owner", "pally", "palmy", "paltry", "pappy",
	"parky", "part-timer", "passer", "paster", "pasty", "patchy", "pater", "pawky",
	"peachy", "pearler", "pearly", "pedaler", "peppy", "perky", "pesky", "peter",
	"petty", "phony", "picky", "piggy", "piny", "pitchy", "pithy", "planer",
	"plashy", "platy", "player", "plucky", "plumber", "plummy", "plumy", "podgy",
	"poky", "polisher", "porky", "porter", "portly", "poster", "potty", "preachy",
	"presenter", "pretender", "pretty", "prickly", "pricy", "priestly", "prim",
	"primer", "princely", "printer", "prissy", "privateer", "privy", "prompter",
	"prosy", "pudgy", "puffer", "puffy", "pulpy", "punchy", "puny", "pushy",
	"pussy", "quaggy", "quaky", "queasy", "queenly", "racy", "rainy", "randy",
	"rangy", "ranker", "rattly", "ratty", "raunchy", "ready", "recorder", "red",
	"reedy", "renter", "retailer", "right-hander", "right-winger", "rimy", "risky",
	"ritzy", "roaster", "rocky", "roily", "rooky", "roomy", "ropy", "rosy", "rowdy",
	"ruddy", "runny", "rusher", "rushy", "rusty", "rutty", "sad", "salter", "salty",
	"sampler", "sandy", "sappy", "sassy", "saucy", "savvy", "scabby", "scaly",
	"scanty", "scary", "scraggly", "scraggy", "scraper", "scrappy", "scrawny",
	"screwy", "scrubby", "scruffy", "scungy", "scurvy", "seamy", "second-rater",
	"seconder", "seedy", "seemly", "serer", "sexy", "shabby", "shady", "shaggy",
	"shaky", "shapely", "shifty", "shiny", "shirty", "shoddy", "showy", "shrubby",
	"shy", "sickly", "sightly", "signaler", "signer", "silky", "silly", "sketchy",
	"skewer", "skimpy", "skinny", "slaphappy", "slaty", "slaver", "sleazy",
	"sleepy", "slim", "slimsy", "slimy", "slinky", "slippy", "sloppy", "sly",
	"smarmy", "smelly", "smoky", "smug", "snaky", "snappy", "snatchy", "snazzy",
	"sneaker", "sniffy", "snooty", "snotty", "snowy", "snuffer", "snuffy", "snug",
	"soapy", "soggy", "solder", "sonsy", "sooty", "soppy", "sorry", "soupy",
	"souther", "southerner", "speedy", "spicy", "spiffy", "spiky", "spindly",
	"spiny", "splashy", "spongy", "spooky", "spoony", "sporty", "spotty",
	"spreader", "sprightly", "springer", "springy", "spry", "squashy", "squat",
	"squatty", "squiffy", "stagy", "stalky", "stapler", "starchy", "starer",
	"starest", "starry", "stately", "steady", "stealthy", "steamy", "stingy",
	"stocker", "stocky", "stodgy", "stony", "stormy", "streaky", "streamy",
	"stretcher", "stretchy", "stringy", "striper", "stripy", "strong", "stroppy",
	"stuffy", "stumpy", "sturdy", "submariner", "sulky", "sultry", "sunny", "surly",
	"swagger", "swanky", "swarthy", "sweaty", "tacky", "talky", "tan", "tangy",
	"tardy", "tasty", "tatty", "tawdry", "techy", "teenager", "teeny", "teetotaler",
	"tester", "testy", "tetchy", "thin", "third-rater", "thirsty", "thorny",
	"thready", "thrifty", "throaty", "tidy", "timely", "tinny", "tiny", "tipsy",
	"tony", "toothy", "toper", "touchy", "trader", "trashy", "trendy", "tricksy",
	"tricky", "trim", "trimer", "true", "trusty", "tubby", "turfy", "tweedy",
	"twiggy", "ugly", "unfriendly", "ungainly", "ungodly", "unhappy", "unhealthy",
	"unholy", "unruly", "untidy", "vasty", "vest", "viewy", "wacky", "wan", "wary",
	"washy", "waster", "wavy", "waxy", "weakly", "wealthy", "weary", "webby",
	"weedy", "weensy", "weeny", "weepy", "weighty", "welsher", "wet", "whacky",
	"whimsy", "wholesaler", "wieldy", "wily", "windy", "wintery", "wintry", "winy",
	"wiry", "wispy", "witty", "wonky", "woodsy", "woody", "woolly", "woozy",
	"wordy", "worldly", "wormy", "worthy", "wry", "yare", "yeasty", "young",
	"yummy", "zany", "zippy",
}
