package haiku

// These words sources from WordNet, downloaded from https://wordnet.princeton.edu/.
// See included LICENSE.WordNet.txt for details.

// Nouns to be used in Haiku naming.
var Nouns Words = []string{
	"aardwolf", "abacus", "aboideau", "aboiteau", "abscissa", "acanthus", "acarus",
	"acciaccatura", "acetabulum", "achaemenid", "acicula", "aciculum", "acinus",
	"acromion", "actinia", "actinozoan", "addendum", "adenocarcinoma", "adenoma",
	"adieu", "adytum", "aecidium", "aecium", "aerobium", "aggiornamento", "agnomen",
	"agon", "agora", "agouti", "ala", "alewife", "alkali", "allodium", "alluvium",
	"alodium", "altocumulus", "altostratus", "alula", "alumna", "alumnus",
	"alveolus", "amanuensis", "ambulacrum", "ameba", "amniocentesis", "amnion",
	"amoeba", "amoebiasis", "amora", "amoretto", "amorino", "amphiarthrosis",
	"amphimixis", "amphioxus", "amphisbaena", "amphithecium", "amphora", "ampulla",
	"amygdala", "anabasis", "anacoluthon", "anacrusis", "anaerobium", "anagnorisis",
	"analemma", "analysis", "anamnesis", "anamorphosis", "anaptyxis", "anastomosis",
	"anatto", "ancon", "androclinium", "androecium", "androsphinx", "angelfish",
	"angioma", "animalculum", "anlage", "annulus", "anta", "antalkali", "antefix",
	"antenna", "antependium", "anthelion", "anthelix", "anthemion", "antheridium",
	"anthodium", "anthozoan", "anthrax", "anticlinorium", "antihelix", "antihero",
	"antiserum", "antithesis", "antitragus", "antrum", "anus", "aorta", "apex",
	"aphelion", "aphis", "apodosis", "apomixis", "aponeurosis", "apophysis",
	"aposiopesis", "apothecium", "apotheosis", "apparatus", "appendix",
	"appoggiatura", "apsis", "aqua", "aquarium", "arboretum", "arcanum",
	"archegonium", "archerfish", "archesporium", "archipelago", "areola", "argali",
	"argumentum", "arietta", "arista", "armamentarium", "arsis", "arteriosclerosis",
	"aruspex", "ascesis", "ascidium", "ascogonium", "ascus", "ash", "ashkenazi",
	"aspergillosis", "aspergillum", "aspergillus", "aspersorium", "assagai",
	"astragalus", "asyndeton", "atheroma", "atherosclerosis", "atmolysis", "atrium",
	"auditorium", "aura", "aureus", "auricula", "aurora", "auspex", "autocatalysis",
	"autochthon", "automaton", "avitaminosis", "ax", "axilla", "bacchant",
	"bacchius", "bacillus", "bacteriostasis", "baculum", "ballista", "bambino",
	"ban", "bandeau", "bandit", "banjo", "barklouse", "barramundi", "base",
	"basidium", "basileus", "basso", "bastinado", "bateau", "batfish", "beadsman",
	"beau", "beef", "behoof", "bersagliere", "bheesty", "bibliotheca",
	"bicentenary", "bijou", "bilbo", "billfish", "bimbo", "bisectrix", "blackfish",
	"blackfoot", "blastema", "blastula", "blindfish", "blowfish", "bluefish",
	"boarfish", "boletus", "bolivar", "bolshevik", "bonefish", "bongo", "bonito",
	"booklouse", "bookshelf", "borax", "borborygmus", "bordereau", "boschbok",
	"botargo", "boxfish", "brachium", "brainchild", "branchia", "brant", "bravado",
	"bravo", "bregma", "broadleaf", "bronchus", "brother", "bryozoan", "bubo",
	"bucko", "bucktooth", "buffalo", "bulla", "bund", "bureau", "bursa", "bus",
	"butterfish", "byssus", "cactus", "caduceus", "caecum", "caestus", "caesura",
	"calamus", "calathus", "calcaneum", "calculus", "caldarium", "calf", "calico",
	"calix", "callus", "calx", "calyx", "cambium", "camera", "canaliculus",
	"candelabrum", "candlefish", "canthus", "canula", "canzone", "capitulum",
	"capriccio", "caput", "carabiniere", "carbonado", "carcinoma", "cargo",
	"carina", "carolus", "carpogonium", "carpus", "caryatid", "caryopsis",
	"castrato", "catabasis", "cataclasis", "catalo", "catalysis", "catena",
	"catfish", "cathar", "cathexis", "cattalo", "caudex", "caulis", "cavatina",
	"cavefish", "cavetto", "cecum", "cella", "cembalo", "centesimo", "centrum",
	"cephalothorax", "cercaria", "cercus", "cerebellum", "cerebrum", "cervix",
	"cesura", "chaeta", "chalaza", "chalutz", "chapati", "chapatti", "chapeau",
	"chasid", "chassid", "chateau", "chazan", "cheder", "chela", "chelicera",
	"cherub", "chiasma", "chiasmus", "child", "chilli", "chitarrone", "chlamys",
	"chondroma", "choragus", "choriambus", "chou", "chromonema", "chrysalis",
	"chuvash", "ciborium", "cicada", "cicala", "cicatrix", "cicerone", "cicisbeo",
	"cilium", "cimex", "cinerarium", "cingulum", "cirrocumulus", "cirrostratus",
	"cirrus", "cisco", "cisterna", "clarino", "claro", "clepsydra", "clinandrium",
	"clingfish", "clitellum", "cloaca", "clostridium", "cloverleaf", "clypeus",
	"coagulum", "coalfish", "coccus", "coccyx", "cochlea", "codex", "codfish",
	"coelenteron", "coenurus", "cognomen", "cognosente", "coleorhiza", "collegium",
	"colloquium", "colluvium", "collyrium", "colon", "colossus", "columbarium",
	"columella", "coma", "comatula", "comedo", "commando", "concertante",
	"concertino", "concerto", "concha", "condottiere", "condyloma", "conferva",
	"congius", "conidium", "conjunctiva", "conquistador", "consortium", "contagium",
	"continuum", "contralto", "conversazione", "convolvulus", "copula", "corbicula",
	"corium", "cornea", "cornu", "corona", "corpus", "corrigendum", "cortex",
	"cortina", "corybant", "coryphaeus", "costa", "cothurnus", "couteau", "cowfish",
	"coxa", "crambo", "cranium", "crasis", "crawfish", "crayfish", "credendum",
	"crematorium", "crescendo", "cribellum", "crisis", "crissum", "crista",
	"criterion", "crus", "crusado", "crux", "cruzado", "cry", "ctenidium",
	"cubiculum", "culex", "culpa", "cultus", "cumulonimbus", "cumulostratus",
	"cumulus", "curia", "curriculum", "custos", "cuticula", "cutis", "cuttlefish",
	"cyclops", "cyclosis", "cylix", "cyma", "cymatium", "cypsela", "cysticercus",
	"dado", "dago", "daimio", "damselfish", "datum", "dealfish", "decemvir",
	"decennium", "decidua", "definiendum", "definiens", "delphinium", "denarius",
	"dentalium", "dermatosis", "desideratum", "desperado", "devilfish", "diaeresis",
	"diagnosis", "dialysis", "diaphysis", "diapophysis", "diarthrosis",
	"diastalsis", "diastasis", "diastema", "diathesis", "diazo", "dibbuk",
	"dichasium", "dictum", "dido", "dieresis", "diesis", "differentia",
	"dilettante", "diluvium", "dingo", "diplococcus", "discobolos", "discus",
	"diva", "diverticulum", "divertimento", "djinni", "dodo", "dogfish", "dogma",
	"dogtooth", "dollarfish", "domatium", "domino", "dormouse", "dorsum", "drachma",
	"drawknife", "drosophila", "drumfish", "dryad", "duo", "duodenum", "dupondius",
	"duumvir", "dwarf", "dybbuk", "ecchymosis", "ecclesia", "ecdysis", "echidna",
	"echinococcus", "echinus", "echo", "ectozoan", "eddo", "edema", "effluvium",
	"eidolon", "eisegesis", "eisteddfod", "elenchus", "elf", "ellipsis", "eluvium",
	"elytron", "embargo", "embolus", "emphasis", "emporium", "enarthrosis",
	"encephalitis", "encephaloma", "encephalon", "enchiridion", "enchondroma",
	"encomium", "endameba", "endamoeba", "endocardium", "endocranium",
	"endometrium", "endosteum", "endostosis", "endothecium", "endothelioma",
	"endothelium", "endozoan", "enema", "enneahedron", "ens", "entameba",
	"entamoeba", "entasis", "enteron", "entozoan", "epencephalon", "epenthesis",
	"epexegesis", "ephemera", "ephemeris", "ephemeron", "ephor", "epicalyx",
	"epicanthus", "epicardium", "epicedium", "epiclesis", "epididymis",
	"epigastrium", "epiglottis", "epimysium", "epiphenomenon", "epiphysis",
	"episternum", "epithalamion", "epithelioma", "epithelium", "epizoan",
	"epyllion", "equilibrium", "equisetum", "eringo", "erratum", "eryngo",
	"esophagus", "etymon", "eucalyptus", "eupatrid", "euripus", "exanthema",
	"executrix", "exegesis", "exemplum", "exordium", "exostosis", "extremum",
	"eyetooth", "eyir", "eyrir", "fabliau", "facia", "facula", "faeroese",
	"fallfish", "famulus", "faroese", "farrago", "fascia", "fasciculus", "fatso",
	"fauna", "fecula", "fedayee", "fellah", "femur", "fenestella", "fenestra",
	"feria", "fermata", "ferula", "festschrift", "fetial", "fez", "fiasco",
	"fibrilla", "fibroma", "fibula", "fico", "fideicommissum", "fieldmouse", "fig.",
	"filaria", "filefish", "filum", "fimbria", "fish", "fishwife", "fistula",
	"flabellum", "flagellum", "flagstaff", "flambeau", "flamen", "flamingo",
	"flatfish", "flatfoot", "flittermouse", "flocculus", "floccus", "flora",
	"floreat", "florilegium", "flyleaf", "focus", "folium", "foot", "foramen",
	"forceps", "forefoot", "foretooth", "formicarium", "formula", "fornix",
	"fortis", "forum", "fossa", "fovea", "foveola", "fractocumulus",
	"fractostratus", "fraenum", "frau", "frenulum", "frenum", "fresco",
	"fricandeau", "fricando", "frijol", "frogfish", "frons", "frustum", "fucus",
	"fulcrum", "fumatorium", "fundus", "fungus", "funiculus", "furcula", "furculum",
	"furfur", "galea", "gambado", "gametangium", "gametoecium", "gammadion",
	"ganglion", "garfish", "gas", "gastrula", "gateau", "gazebo", "gecko",
	"gelsemium", "gemeinschaft", "gemma", "gemsbok", "gemsbuck", "generatrix",
	"genesis", "genius", "gens", "genu", "genus", "germen", "gesellschaft",
	"gestalt", "ghetto", "gingiva", "gingko", "ginglymus", "ginkgo", "gippo",
	"glabella", "gladiolus", "glans", "glioma", "glissando", "globefish",
	"globigerina", "glochidium", "glomerulus", "glossa", "glottis", "glutaeus",
	"gluteus", "gnosis", "go", "goatfish", "gobo", "godchild", "goldfish",
	"gomphosis", "gonidium", "gonion", "gonococcus", "goodwife", "goose",
	"goosefish", "gorgoneion", "gospodin", "goy", "gps", "graf", "graffito",
	"grandchild", "granuloma", "gravamen", "grosz", "grotto", "guilde",
	"guitarfish", "gumma", "gurnar", "gutta", "gymnasium", "gynaeceum", "gynaecium",
	"gynecium", "gynoecium", "gyrus", "hadj", "haematolysis", "haematoma",
	"haematozoon", "haemodialysis", "haemolysis", "haemoptysis", "haeres",
	"haftarah", "hagfish", "haggada", "hajj", "haler", "half", "halfpenny",
	"hallah", "hallux", "halo", "halter", "hamulus", "haphtarah", "haredi",
	"haruspex", "hasid", "hassid", "haustellum", "haustorium", "hazzan",
	"hectocotylus", "heder", "heldentenor", "heliozoan", "helix", "hematolysis",
	"hematoma", "hematozoon", "hemelytron", "hemielytron", "hemodialysis",
	"hemolysis", "hemoptysis", "hendecahedron", "heraclid", "heraklid", "herbarium",
	"herm", "herma", "hernia", "hero", "herr", "hetaera", "hetaira", "hibernaculum",
	"hieracosphinx", "hilum", "hilus", "himation", "hippocampus", "hippopotamus",
	"his", "hobo", "hogfish", "homunculus", "honorarium", "hoof", "horologium",
	"housewife", "humerus", "hydra", "hydromedusa", "hydrozoan", "hymenium",
	"hymenopteran", "hypanthium", "hyperostosis", "hypha", "hypnosis",
	"hypochondrium", "hypogastrium", "hypogeum", "hypophysis", "hypostasis",
	"hypothalamus", "hypothesis", "hyrax", "iamb", "ibex", "ichthyosaur",
	"ichthyosaurus", "iconostas", "icosahedron", "ideatum", "igbo", "igorrote",
	"ilium", "imago", "imperium", "impi", "incubus", "incus", "index", "indigo",
	"indumentum", "indusium", "infundibulum", "ingush", "innuendo", "inoculum",
	"insectarium", "insula", "intaglio", "interleaf", "intermezzo", "interregnum",
	"interrex", "intima", "involucellum", "involucre", "involucrum", "iris", "irs",
	"is", "ischium", "isthmus", "jackaroo", "jackfish", "jackknife", "jambeau",
	"jellyfish", "jewelfish", "jewfish", "jingo", "jinni", "jo", "jus", "kaddish",
	"kalmuc", "katabasis", "keeshond", "kibbutz", "killifish", "kingfish", "knife",
	"kohlrabi", "krona", "krone", "kroon", "kylix", "labarum", "labellum", "labium",
	"labrum", "lactobacillus", "lacuna", "lacunar", "lamella", "lamia", "lamina",
	"lapillus", "lapith", "larva", "larynx", "lasso", "lat", "latex", "latifundium",
	"lavabo", "leaf", "lecythus", "lemma", "lemniscus", "lenis", "lentigo",
	"leonid", "lepidopteran", "leprosarium", "leptocephalus", "lepton", "leu",
	"leucocytozoan", "lev", "lex", "libra", "libretto", "lied", "life", "ligula",
	"likuta", "limbus", "limen", "limes", "limulus", "lingo", "lingua", "lionfish",
	"lipoma", "lira", "liriodendron", "lit", "litas", "lixivium", "loaf", "loculus",
	"locus", "loggia", "logion", "lomentum", "longobard", "lorica", "loti", "louse",
	"luba", "lubritorium", "lumbi", "lumen", "lumpfish", "lungfish", "lunula",
	"lur", "lustre", "lymphangitis", "lymphoma", "lymphopoiesis", "lysis", "lytta",
	"maar", "macaroni", "maccaroni", "machzor", "macronucleus", "macrosporangium",
	"macula", "madame", "mademoiselle", "madrono", "maestro", "mafioso", "magma",
	"magnifico", "magus", "mahzor", "malleolus", "malleus", "mamilla", "mamma",
	"mammilla", "man", "mandingo", "mango", "manifesto", "manservant", "manteau",
	"mantis", "manubrium", "marchesa", "marchese", "maremma", "markka", "marsupium",
	"mass", "matrix", "matzo", "mausoleum", "maxilla", "maximum", "media",
	"mediastinum", "medium", "medulla", "medusa", "megaron", "megasporangium",
	"megillah", "meiosis", "melanoma", "melisma", "memento", "memorandum",
	"meniscus", "menstruum", "mesenteron", "mesothorax", "mestizo", "metacarpus",
	"metamorphosis", "metanephros", "metastasis", "metatarsus", "metathesis",
	"metathorax", "metazoan", "metempsychosis", "metencephalon", "mezuzah",
	"miasma", "microanalysis", "micrococcus", "micronucleus", "microsporangium",
	"midrash", "midwife", "milieu", "milium", "milkfish", "millennium", "mina",
	"minimum", "ministerium", "minutia", "minyan", "miosis", "mir", "miracidium",
	"mishna", "mitochondrion", "mitzvah", "modiolus", "modulus", "momentum",
	"momus", "monad", "monkfish", "monochasium", "monopodium", "monopteron",
	"monopteros", "monseigneur", "monsieur", "monsignor", "mooncalf", "moonfish",
	"mora", "moratorium", "morceau", "moresco", "morisco", "morphallaxis",
	"morphosis", "morse", "morula", "mosasaurus", "moshav", "moslem", "mosquito",
	"motto", "mouse", "mucosa", "mucro", "mudejar", "mudfish", "mulatto",
	"multipara", "murex", "muskellunge", "mycelium", "mycetoma", "mycobacterium",
	"mycorrhiza", "myelencephalon", "myiasis", "myocardium", "myofibrilla", "myoma",
	"myosis", "myrmidon", "mythos", "myxoma", "naevus", "naiad", "naos",
	"narcissus", "naris", "nasopharynx", "natatorium", "naumachia", "nauplius",
	"nautilus", "navaho", "navajo", "nebula", "necropolis", "needlefish",
	"negrillo", "negrito", "negro", "nemesis", "nephridium", "nereid",
	"neurohypophysis", "neuroma", "neuropteron", "neurosis", "nevus", "nibelung",
	"nidus", "niello", "nilgai", "nimbostratus", "nimbus", "no", "noctiluca",
	"nodus", "nomen", "notum", "noumenon", "nova", "novella", "novena", "nubecula",
	"nucellus", "nucha", "nucleolus", "nucleus", "nullipara", "numbfish", "numen",
	"nympha", "oarfish", "oasis", "obelus", "obligato", "obolus", "occiput",
	"oceanarium", "oceanid", "ocellus", "ochrea", "octahedron", "octopus", "oculus",
	"odeum", "oldwife", "oleum", "omasum", "omayyad", "omentum", "ommatidium",
	"ommiad", "onager", "oogonium", "ootheca", "operculum", "optimum", "organa",
	"organon", "orthopteron", "os", "osculum", "osteoma", "ostium", "othman",
	"ovolo", "ovotestis", "ovum", "ox", "oxymoron", "paddlefish", "paisa", "palea",
	"palestra", "palingenesis", "pallium", "palmetto", "palpus", "pancratium",
	"panettone", "paparazzo", "paperknife", "papilla", "papilloma", "pappus",
	"papula", "papyrus", "parabasis", "paraleipsis", "paralysis", "paramecium",
	"parament", "paraphysis", "parapodium", "parapraxis", "paraselene", "parashah",
	"parasyntheton", "parazoan", "parenthesis", "parergon", "parhelion", "paries",
	"parrotfish", "parulis", "pastorale", "patagium", "patella", "paterfamilias",
	"patina", "pea", "peccadillo", "pecten", "pedalo", "pekinese", "pelvis",
	"penetralia", "penicillium", "penis", "penknife", "penna", "penni", "penny",
	"pentahedron", "pentimento", "penumbra", "peplum", "pericardium",
	"perichondrium", "pericranium", "peridium", "perigonium", "perihelion",
	"perinephrium", "perineum", "perionychium", "periosteum", "periphrasis",
	"peristalsis", "perithecium", "peritoneum", "persona", "pes", "petechia",
	"pfennig", "phalange", "phallus", "pharynx", "phenomenon", "philodendron",
	"phlyctaena", "phyle", "phyllotaxis", "phylloxera", "phylogenesis", "phylum",
	"pigfish", "pileum", "pileus", "pinetum", "pinfish", "pinko", "pinna",
	"pinnula", "pipefish", "pirog", "piscina", "pithecanthropus", "pithos",
	"placebo", "placenta", "planetarium", "planula", "plasmodesma", "plasmodium",
	"plateau", "plectron", "plenum", "pleura", "pleuron", "plica", "ploughman",
	"pneumobacillus", "pneumococcus", "pocketknife", "podetium", "podium", "polis",
	"pollex", "pollinium", "polychasium", "polyhedron", "polyparium", "polypus",
	"polyzoan", "polyzoarium", "pons", "pontifex", "portamento", "portico",
	"portmanteau", "postliminium", "potato", "praenomen", "praxis", "predella",
	"premaxilla", "prenomen", "presa", "primigravida", "primipara", "primo",
	"primordium", "principium", "proboscis", "proglottid", "prognosis",
	"prolegomenon", "prolepsis", "promycelium", "pronephros", "pronucleus",
	"propositus", "proptosis", "propylaeum", "propylon", "proscenium",
	"prosencephalon", "prosthesis", "prostomium", "protasis", "prothalamion",
	"prothallium", "prothallus", "prothorax", "protonema", "protozoan",
	"proventriculus", "proviso", "prytaneum", "psalterium", "pseudopodium",
	"psychoneurosis", "psychosis", "pterygium", "pteryla", "ptosis", "pubis",
	"pudendum", "pul", "pulvillus", "pulvinus", "punchinello", "pupa", "puparium",
	"putamen", "putto", "pycnidium", "pygidium", "pylorus", "pyxidium", "pyxis",
	"qaddish", "quadrennium", "quadriga", "quale", "quantum", "quarterstaff",
	"quezal", "quinquennium", "quiz", "rabato", "rabbitfish", "rachis", "radius",
	"radix", "radula", "ramentum", "ramus", "ranula", "ranunculus", "raphe",
	"raphide", "ratfish", "real", "rearmouse", "rectrix", "rectum", "rectus",
	"redfish", "redia", "referendum", "refugium", "regulus", "relatum", "remex",
	"reseau", "residuum", "responsum", "rete", "retiarius", "reticulum", "retina",
	"retinaculum", "rhabdomyoma", "rhachis", "rhinencephalon", "rhizobium",
	"rhombus", "rhonchus", "rhyton", "ribbonfish", "ricercare", "rickettsia",
	"rilievo", "rima", "rockfish", "rom", "rondeau", "rosarium", "rosefish",
	"rostellum", "rostrum", "rotl", "rouleau", "ruga", "rumen", "sacrarium",
	"sacrum", "saguaro", "sailfish", "salesperson", "salmonella", "salpa",
	"salpinx", "saltarello", "salvo", "sanctum", "sanitarium", "santims", "saphena",
	"sarcophagus", "sartorius", "sassanid", "sawfish", "scaldfish", "scalenus",
	"scapula", "scarabaeus", "scarf", "schatchen", "schema", "scherzando",
	"scherzo", "schmo", "scholium", "schul", "schutzstaffel", "scirrhus",
	"scleroma", "sclerosis", "sclerotium", "scolex", "scopula", "scoria", "scotoma",
	"scriptorium", "scrotum", "scudo", "scutellum", "scutum", "scyphistoma",
	"scyphozoan", "scyphus", "secondo", "segno", "seleucid", "self", "senor",
	"sensillum", "sent", "sente", "senusi", "separatrix", "sephardi", "septarium",
	"septennium", "septum", "sequela", "sequestrum", "seraph", "serum",
	"sestertium", "seta", "sgraffito", "shabbas", "shabbat", "shacko", "shadchan",
	"shako", "shammas", "sheaf", "sheatfish", "shelf", "shellfish", "shinleaf",
	"shittah", "shmo", "shofar", "shophar", "shrewmouse", "shul", "siddur",
	"siglos", "signior", "signora", "signorina", "siliqua", "silva", "silverfish",
	"simulacrum", "sinciput", "sinfonia", "sistrum", "situla", "smalto",
	"snaggletooth", "snailfish", "snipefish", "socman", "sol", "solarium",
	"solatium", "soldo", "solfeggio", "solidus", "solo", "solum", "soma", "soprano",
	"sordino", "sorosis", "sorus", "sovkhoz", "spadefish", "spadix", "spearfish",
	"spectrum", "speculum", "spermatium", "spermatogonium", "spermatozoon",
	"spermogonium", "sphinx", "spica", "spiculum", "spirillum", "splayfoot",
	"splenius", "sporangium", "sporogonium", "sporozoan", "springhaas", "spumone",
	"sputum", "squama", "squash", "squilla", "squirrelfish", "squiz", "stadium",
	"stamen", "staminodium", "stapes", "staphylococcus", "starets", "starfish",
	"stele", "stemma", "stenosis", "stepchild", "sternum", "stigma", "stimulus",
	"stipes", "stirps", "stoa", "stockfish", "stoma", "stomodaeum", "stomodeum",
	"stonefish", "stotinka", "strappado", "stratocumulus", "stratum", "stratus",
	"streptococcus", "stretto", "stria", "strobilus", "stroma", "struma", "stucco",
	"stylopodium", "stylops", "stylus", "subcortex", "subdelirium", "subgenus",
	"subindex", "submucosa", "subphylum", "substratum", "succedaneum", "succubus",
	"suckerfish", "suckfish", "sudarium", "sudatorium", "sulcus", "summa",
	"sunfish", "supercargo", "superhero", "supernova", "superstratum",
	"surgeonfish", "swami", "sweetiewife", "swellfish", "swordfish", "syconium",
	"syllabus", "syllepsis", "symphysis", "sympodium", "symposium", "synapsis",
	"synarthrosis", "synclinorium", "syncytium", "syndesmosis", "synopsis",
	"syntagma", "synthesis", "syphiloma", "syrinx", "syssarcosis", "tableau",
	"taenia", "tallith", "talus", "tapetum", "tarantula", "tarsometatarsus",
	"tarsus", "tax", "taxi", "taxon", "tectrix", "tegmen", "tela", "telamon",
	"telangiectasia", "telium", "tempo", "tenaculum", "tenderfoot", "tenia",
	"tenuis", "teraph", "teras", "teredo", "tergum", "terminus", "terrarium",
	"terzetto", "tessera", "testa", "testis", "testudo", "tetrahedron",
	"tetraskelion", "thalamencephalon", "thalamus", "thallus", "theca", "thesaurus",
	"thesis", "thickleaf", "thief", "tholos", "thorax", "thrombus", "thymus",
	"thyrse", "thyrsus", "tibia", "tilefish", "tintinnabulum", "tiro", "titmouse",
	"toadfish", "tobacco", "tomato", "tomentum", "tondo", "tonneau", "tooth",
	"tophus", "topos", "tornado", "torpedo", "torso", "torus", "touraco",
	"trabecula", "trachea", "traditor", "tragus", "trapezium", "trapezohedron",
	"trauma", "treponema", "trichina", "triclinium", "triennium", "triforium",
	"triggerfish", "trihedron", "triskelion", "trisoctahedron", "triumvir",
	"trivium", "trochlea", "tropaeolum", "trousseau", "trunkfish", "tryma", "tuba",
	"turf", "tympanum", "ubermensch", "ugli", "uighur", "ulna", "ultimatum",
	"umbilicus", "umbo", "umbra", "uncus", "uredinium", "uredium", "uredo",
	"uredosorus", "urethra", "urinalysis", "uterus", "utriculus", "uvula", "vacuum",
	"vagina", "vagus", "vallecula", "vaporetto", "varix", "vas", "vasculum",
	"velamen", "velarium", "velum", "vena", "ventriculus", "vermis", "verruca",
	"vertebra", "vertex", "vertigo", "vesica", "veto", "vexillum", "viaticum",
	"viator", "vibraculum", "vibrissa", "villus", "vimen", "vinculum", "virago",
	"virtuoso", "vis", "vita", "vitellus", "vitta", "vivarium", "volcano",
	"volkslied", "volta", "volva", "vortex", "vorticella", "vox", "vulva", "wahabi",
	"wanderjahr", "weakfish", "werewolf", "wharf", "whitefish", "wife", "wolf",
	"wolffish", "woodlouse", "wreckfish", "wunderkind", "xiphisternum", "yeshiva",
	"yogi", "yourself", "zamindari", "zecchino", "zero", "zoaea", "zoea", "zoon",
	"zoonosis", "zoosporangium",
}
